
```{r}
challenger = read.csv("/Users/adhara/Dropbox/ucberkeley/271 Adv stats/Lab1/challenger.csv", header=TRUE)
```


####### Q4 ##########
```{r}
challenger$Pressure = factor(challenger$Pressure)
challenger$ratio = challenger$O.ring / challenger$Number
plot(x=challenger$ratio, y=challenger$Temp)
```
```{r}
plot(x=challenger$ratio, y=challenger$Pressure)
```
```{r}
challenger
```

####### 4B ##########
```{r}
challenger$incidence = ifelse(challenger$O.ring > 0, 1, 0)
mod.fit = glm(formula = ratio ~ Temp + Pressure, family=binomial(link=logit), data=challenger)
mod.fit.incidence = glm(formula = incidence ~ Temp + Pressure, family=binomial(link=logit), data=challenger)
# Warning message:
# In eval(family$initialize) : non-integer #successes in a binomial glm!

mod.fit
```
```{r}
summary(mod.fit)
```

```{r}
mod.fit.incidence
```
```{r}
summary(mod.fit.incidence)
```

####### 4C ##########
```{r}
library(package = car)
Anova(mod.fit, test = "LR")
```
```{r}
Anova(mod.fit.incidence, test = "LR")
```
```{r}
anova(mod.fit, test = "Chisq")
```
```{r}
anova(mod.fit.incidence, test = "Chisq")
```

####### Q5 ##########
####### 5A ##########
```{r}
mod.fit2 = glm(formula = ratio ~ Temp , family=binomial(link=logit), data=challenger)
summary(mod.fit2)
```

```{r}
mod.fit2.incidence = glm(formula = incidence ~ Temp , family=binomial(link=logit), data=challenger)
summary(mod.fit2.incidence)
```

####### 5B ##########
```{r}
b0 = mod.fit2.incidence$coefficients[["(Intercept)"]]
b1 = mod.fit2.incidence$coefficients[["Temp"]]

eq2 = function(x){exp(b0 + b1*x) / (1+ exp( b0 + b1*x))}
curve(eq2, from=31, to=81, col='red')

b0 = mod.fit2$coefficients[["(Intercept)"]]
b1 = mod.fit2$coefficients[["Temp"]]

eq1 = function(x){exp(b0 + b1*x) / (1+ exp( b0 + b1*x))}
curve(eq1, from=31, to=81, col='blue', add=TRUE)
```

# TODO -- plot expected number of failures

####### 5C ##########
# page 89
```{r}
predict.data = data.frame(Temp = seq(from = 31, to = 81))
# linear.pred = predict(object = mod.fit2, newdata = predict.data, type = "link" , se = TRUE)
# linear.pred

alpha = 0.05
ci.pi = function(newdata, mod.fit.obj, alpha) {
  linear.pred = predict(object = mod.fit.obj, newdata = newdata, type = "link", se= TRUE)
  CI.lin.pred.lower = linear.pred$fit - qnorm(p = 1-alpha/2) * linear.pred$se
  CI.lin.pred.upper = linear.pred$fit + qnorm(p = 1-alpha/2) * linear.pred$se
  CI.pi.lower = exp(CI.lin.pred.lower) / (1+ exp(CI.lin.pred.lower))
  CI.pi.upper = exp(CI.lin.pred.upper) / (1+ exp(CI.lin.pred.upper))
  list(lower = CI.pi.lower, upper = CI.pi.upper)
}
```

```{r}
curve(expr=ci.pi(newdata = data.frame(Temp = x), mod.fit.obj = mod.fit2, alpha=0.05)$upper, lty = "dotdash", xlim=c(31,81))
curve(expr=ci.pi(newdata = data.frame(Temp = x), mod.fit.obj = mod.fit2, alpha=0.05)$lower, lty = "dotdash", add = TRUE, xlim=c(31,81))

# pi.hat = exp(linear.pred$fit) / (1 + exp(linear.pred$fit))
# CI.lin.pred = linear.pred$fit + qnorm(p = c(alpha/2, 1-alpha/2)) * linear.pred$se.fit
# CI.pi = exp(CI.lin.pred) / (1 + exp(CI.lin.pred))
```

```{r}
curve(expr=ci.pi(newdata = data.frame(Temp = x), mod.fit.obj = mod.fit2.incidence, alpha=0.05)$upper, lty = "dotdash", xlim=c(31,81))
curve(expr=ci.pi(newdata = data.frame(Temp = x), mod.fit.obj = mod.fit2.incidence, alpha=0.05)$lower, lty = "dotdash", add = TRUE, xlim=c(31,81))
# pi.hat = exp(linear.pred$fit) / (1 + exp(linear.pred$fit))
# CI.lin.pred = linear.pred$fit + qnorm(p = c(alpha/2, 1-alpha/2)) * linear.pred$se.fit
# CI.pi = exp(CI.lin.pred) / (1 + exp(CI.lin.pred))
```